export const workflow = {
  id: 'demo-onboarding',
  title: 'Customer Onboarding',
  userId: 'demo',
  createdAt: new Date(),
  updatedAt: new Date(),
  items: [
    {
      id: '1',
      type: 'init',
      content: '',
      subject: '',
      method: 'init',
      x: 0,
      y: 0,
      time: 0,
      level: 1,
      workflowId: 'demo-onboarding',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'a167f4ee-5655-43be-b925-3959f3e9e7d8',
      type: 'message',
      content:
        "Hey!\n\nWelcome to Review Rabbit - we can't wait to finally give your business the recognition it deserves!\n\nBest,\nCharlie",
      subject: 'Welcome to Review Rabbit! 🎉',
      method: 'email',
      x: 0,
      y: 200,
      time: 0,
      level: 2,
      workflowId: 'demo-onboarding',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
}
